### PR TITLE
Update pipeline.yml

### PR DESCRIPTION
**Pull request by weslenng**
This PR updates the current CI/CD to `npm publish` each commit to the master branch
In order to everything work we also need a `NODE_AUTH_TOKEN` secret with a [NPM Access Token (Automation)](https://i.imgur.com/Un088P9.png)

### CODE REVIEW

**Comment by fakenickels** [comment]
10000% wonderful. Totally forgot to upgrade the actions versions themselves! Great clean up as well 💯💯💯

**Comment by smorimoto** [comment]
​The recommended styles is:

```
git config --global user.email "github-actions@github.com"
git config --global user.name "github-actions[bot]"
```

Alternatively, if you want the actor to be the committer, you can do the following:

```
git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
git config --global user.name "${GITHUB_ACTOR}"
```

**Comment by fakenickels** [comment]
Thanks for the tip! @smorimoto 🙏

**Comment by smorimoto** [comment]
The current one is a general account that isn't exactly for your bot, so ideally, you should use the one I showed. ​For example, the Actions team uses the same one I showed you :)
https://github.com/actions/toolkit/blob/2bf7365352507ee52b4017790934cf9cefabc5f4/.github/workflows/update-github.yaml#L25-L26

**Pull request merged**
